# Contextualizing Problems and Data

## Evaluating a data science problem 

## Reseaching solutions 

## Formulating a hypothesis 

## Preparing your data 

# Considering the Art of Feature Creation

## Defining feature creation

## Combining variables

## Understanding binning and discretization

## Using indicator variables

## Transforming distributions 

# Performing Operations on Arrays 

## Using vectorization

In [29]:
import numpy as np
# creating an 2 dimentional array with 3 x 7 as the shape
dataset  = np.array([[2, 3, 4, 5, 6, 7, 8],
                     [4, 3, 5, 2, 6, 7, 3],
                     [7, 4, 3, 2, 6, 8, 1]])

# printing the shape of the array
print(dataset.shape)
# printing the max value of each observation in respectable axis
print(np.max(dataset, axis=0))
print(np.max(dataset, axis=1))
# subtract the max value with the minimmum value of each observation
# in axis 1
print(np.max(dataset, axis=1) - np.min(dataset, axis=1))

(3, 7)
[7 4 5 5 6 8 8]
[8 7 8]
[6 5 7]


## Performing simple arithmetic on vectors and matrices 

In [31]:
import numpy as np

a = np.array([15.0, 20.0, 22.0, 75.0, 40.0, 35.0])

print(a)
# multiplying a float number with an (6, 1) array
a *= .01

print(a)

(6,)
[15. 20. 22. 75. 40. 35.]
[0.15 0.2  0.22 0.75 0.4  0.35]


## Performing matrix vector multiplication

In [57]:
import numpy as np
# making a vector
a = np.array([2, 4, 6, 8])
# making a 2 dimentional matrix
b = np.array([[1, 2, 3, 4],
              [2, 3, 4, 5],
              [3, 4, 5, 6],
              [4, 5, 6, 7]])

# using dot prduct multiplication
c = np.dot(a, b)
print(c)

[ 60  80 100 120]


## Performing matrix multiplication 

In [63]:
import numpy as np
# making a 2 x 4 matrix
a = np.array([[2, 4, 6, 8], 
              [1, 3, 5, 7]])
# making a 4 x 2 matrix
b = np.array([[1, 2],
              [2, 3],
              [3, 4],
              [4, 5]])

print(a.shape)
print(b.shape)
c = np.dot(a, b)
print(c)

(2, 4)
(4, 2)
[[60 80]
 [50 66]]
